<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Luxorka
 * Date: 27.02.13
 * Time: 10:53
 * To change this template use File | Settings | File Templates.
 */

Yii::import('zii.widgets.CMenu');

class LXCMenu extends CMenu {
    private $curModel = null;

    /**
     * Checks whether a menu item is active.
     * This is done by checking if the currently requested URL is generated by the 'url' option
     * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
     * @param array $item the menu item to be checked
     * @param string $route the route of the current request
     * @return boolean whether the menu item is active
     */
    protected function isItemActive($item, $route) {
        $sefname = Yii::app()->request->getQuery('sefname', false);
        $category = Yii::app()->request->getQuery('category', false);

        if ($category !== false) {
            $sefname = $category;
        }

        if ($item['url'] == $_SERVER['REQUEST_URI']) {
            return true;
        } elseif ($sefname !== false && Yii::app()->controller->module->id == 'pages') {
            if ($sefname == $item['node']->sefname) {
                return true;
            } else {
                if ($sefname !== false) {

                    if ($this->curModel === null) {
                        $this->curModel = Categories::model()->findBySefnameObj($sefname);
                    }

                    if ($this->curModel !== null && $this->curModel->parent !== null && $this->curModel->parent->sefname == $item['node']->sefname) {
                        return true;
                    }
                }
            }
        } else {

            if (isset($item['url']) && !strcasecmp(trim($item['url'], '/'), $route)) {
                unset($item['url']['#']);
                if (count($item['url']) > 1) {
                    foreach (array_splice($item['url'], 1) as $name => $value) {
                        if (!isset($_GET[$name]) || $_GET[$name] != $value)
                            return false;
                    }
                }
                return true;

            }
        }
        return false;
    }
}